from os import getenv

TEMPERATURE_SENSOR_DATA_PIN = 25
TEMPERATURE_SENSOR_SCK_PIN = 24

MQTT_HOST = getenv("HIB_MQTT_HOST")
MQTT_PORT = 1883 if getenv("HIB_MQTT_PORT") is None else int(getenv("HIB_MQTT_PORT"))
MQTT_USER = getenv("HIB_MQTT_USER")
MQTT_PASSWORD = getenv("HIB_MQTT_PASSWORD")
MQTT_ROOT_TOPIC = ""

RGB_LED_R_PIN = 12
RGB_LED_G_PIN = 6
RGB_LED_B_PIN = 13

HEATER_LED_INDICATOR_PIN = 21
COOLER_RELAY_PIN = 20

BUZZER_PIN = 26

CLK = 11
MISO = 9
MOSI = 10
CS = 8
